-- MySQL Script generated by MySQL Workbench
-- Mon May  4 19:17:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema amazon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `amazon` ;

-- -----------------------------------------------------
-- Schema amazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amazon` DEFAULT CHARACTER SET utf8 ;
USE `amazon` ;

-- -----------------------------------------------------
-- Table `amazon`.`autors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`autors` ;

CREATE TABLE IF NOT EXISTS `amazon`.`autors` (
  `idautors` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cognom` VARCHAR(45) NULL,
  `direccio` VARCHAR(45) NULL,
  PRIMARY KEY (`idautors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`cataleg_llibres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`cataleg_llibres` ;

CREATE TABLE IF NOT EXISTS `amazon`.`cataleg_llibres` (
  `idlivros` INT NOT NULL AUTO_INCREMENT,
  `preu` REAL UNSIGNED NOT NULL,
  `quantitat` INT UNSIGNED NOT NULL,
  `autor` INT NOT NULL,
  PRIMARY KEY (`idlivros`),
  INDEX `idautors_idx` (`autor` ASC) VISIBLE,
  CONSTRAINT `idautors`
    FOREIGN KEY (`autor`)
    REFERENCES `amazon`.`autors` (`idautors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`clients` ;

CREATE TABLE IF NOT EXISTS `amazon`.`clients` (
  `idclients` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `contrasenya` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idclients`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`factures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`factures` ;

CREATE TABLE IF NOT EXISTS `amazon`.`factures` (
  `idfactures` INT NOT NULL,
  `idclients` INT NOT NULL,
  `idlivros` INT NOT NULL,
  PRIMARY KEY (`idfactures`),
  INDEX `idlivros_idx` (`idlivros` ASC) VISIBLE,
  INDEX `idclients_idx` (`idclients` ASC) VISIBLE,
  CONSTRAINT `idlivros`
    FOREIGN KEY (`idlivros`)
    REFERENCES `amazon`.`cataleg_llibres` (`idlivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idclients`
    FOREIGN KEY (`idclients`)
    REFERENCES `amazon`.`clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
