-- MySQL Script generated by MySQL Workbench
-- Mon May  4 21:41:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema xarxa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xarxa` ;

-- -----------------------------------------------------
-- Schema xarxa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xarxa` DEFAULT CHARACTER SET utf8 ;
USE `xarxa` ;

-- -----------------------------------------------------
-- Table `xarxa`.`amistats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xarxa`.`amistats` ;

CREATE TABLE IF NOT EXISTS `xarxa`.`amistats` (
  `usuaris_idusuaris` VARCHAR(10) NOT NULL,
  `usuaris_idusuaris1` VARCHAR(10) NOT NULL,
  `idamistat` INT NOT NULL,
  `com_conegut` MEDIUMTEXT NOT NULL,
  INDEX `fk_usuaris_has_usuaris_usuaris2_idx` (`usuaris_idusuaris1` ASC) VISIBLE,
  INDEX `fk_usuaris_has_usuaris_usuaris1_idx` (`usuaris_idusuaris` ASC) VISIBLE,
  PRIMARY KEY (`idamistat`),
  CONSTRAINT `fk_usuaris_has_usuaris_usuaris1`
    FOREIGN KEY (`usuaris_idusuaris`)
    REFERENCES `xarxa`.`usuaris` (`idusuaris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuaris_has_usuaris_usuaris2`
    FOREIGN KEY (`usuaris_idusuaris1`)
    REFERENCES `xarxa`.`usuaris` (`idusuaris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xarxa`.`usuaris`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xarxa`.`usuaris` ;

CREATE TABLE IF NOT EXISTS `xarxa`.`usuaris` (
  `idusuaris` VARCHAR(10) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `contrasenya` VARCHAR(10) NOT NULL,
  `amistat` INT NULL,
  PRIMARY KEY (`idusuaris`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `idamistat_idx` (`amistat` ASC) VISIBLE,
  CONSTRAINT `idamistat`
    FOREIGN KEY (`amistat`)
    REFERENCES `xarxa`.`amistats` (`idamistat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xarxa`.`fotografies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xarxa`.`fotografies` ;

CREATE TABLE IF NOT EXISTS `xarxa`.`fotografies` (
  `idfoto` INT NOT NULL AUTO_INCREMENT,
  `lloc` VARCHAR(45) NOT NULL,
  `url` VARCHAR(100) NULL,
  `propietari` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idfoto`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  INDEX `idusuaris_idx` (`propietari` ASC) VISIBLE,
  CONSTRAINT `idusuaris`
    FOREIGN KEY (`propietari`)
    REFERENCES `xarxa`.`usuaris` (`idusuaris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
