-- MySQL Script generated by MySQL Workbench
-- Fri Jun 19 18:31:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema xarxa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xarxa` ;

-- -----------------------------------------------------
-- Schema xarxa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xarxa` DEFAULT CHARACTER SET utf8 ;
USE `xarxa` ;

-- -----------------------------------------------------
-- Table `xarxa`.`usuari`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xarxa`.`usuari` ;

CREATE TABLE IF NOT EXISTS `xarxa`.`usuari` (
  `id_usuari` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `contrasenya` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_usuari`),
  UNIQUE INDEX `id_usuari_UNIQUE` (`id_usuari` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xarxa`.`fotografies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xarxa`.`fotografies` ;

CREATE TABLE IF NOT EXISTS `xarxa`.`fotografies` (
  `id_fotografies` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `propietari` INT UNSIGNED NOT NULL,
  `lloc_foto` VARCHAR(100) NOT NULL,
  `url_foto` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_fotografies`),
  UNIQUE INDEX `id_fotografies_UNIQUE` (`id_fotografies` ASC) VISIBLE,
  UNIQUE INDEX `url_foto_UNIQUE` (`url_foto` ASC) VISIBLE,
  INDEX `fk_fotografies_usuari_idx` (`propietari` ASC) VISIBLE,
  CONSTRAINT `fk_fotografies_usuari`
    FOREIGN KEY (`propietari`)
    REFERENCES `xarxa`.`usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xarxa`.`amistat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xarxa`.`amistat` ;

CREATE TABLE IF NOT EXISTS `xarxa`.`amistat` (
  `usuari_id_user0` INT UNSIGNED NOT NULL,
  `usuari_id_user1` INT UNSIGNED NOT NULL,
  `origen_amistat_user0` MEDIUMTEXT NULL,
  `origen_amistat_user1` MEDIUMTEXT NULL,
  INDEX `fk_usuari_has_usuari_usuari2_idx` (`usuari_id_user1` ASC) VISIBLE,
  INDEX `fk_usuari_has_usuari_usuari1_idx` (`usuari_id_user0` ASC) VISIBLE,
  PRIMARY KEY (`usuari_id_user1`, `usuari_id_user0`),
  CONSTRAINT `fk_usuari_has_usuari_usuari1`
    FOREIGN KEY (`usuari_id_user0`)
    REFERENCES `xarxa`.`usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuari_has_usuari_usuari2`
    FOREIGN KEY (`usuari_id_user1`)
    REFERENCES `xarxa`.`usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
