-- MySQL Script generated by MySQL Workbench
-- Fri Jun 19 19:32:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ampolla
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ampolla` ;

-- -----------------------------------------------------
-- Schema ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ampolla` DEFAULT CHARACTER SET utf8 ;
USE `ampolla` ;

-- -----------------------------------------------------
-- Table `ampolla`.`adreca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`adreca` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`adreca` (
  `id_adreca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` TINYINT(5) UNSIGNED NOT NULL,
  `pis` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `porta` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  `ciutat` VARCHAR(20) NOT NULL,
  `codi_postal` TINYINT(6) UNSIGNED NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_adreca`),
  UNIQUE INDEX `id_adreca_UNIQUE` (`id_adreca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`proveidors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`proveidors` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`proveidors` (
  `idproveidors` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NULL DEFAULT NULL,
  `nif` TINYINT(12) NOT NULL,
  `adreca` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idproveidors`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  UNIQUE INDEX `idproveidors_UNIQUE` (`idproveidors` ASC) VISIBLE,
  INDEX `fk_proveidors_adreca1_idx` (`adreca` ASC) VISIBLE,
  CONSTRAINT `fk_proveidors_adreca1`
    FOREIGN KEY (`adreca`)
    REFERENCES `ampolla`.`adreca` (`id_adreca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`ulleres` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`ulleres` (
  `idulleres` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio` VARCHAR(45) NOT NULL,
  `muntura` ENUM('pasta', 'flotant', 'metal') NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidre` VARCHAR(45) NOT NULL,
  `preu` DECIMAL(6,2) NOT NULL,
  `proveidor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idulleres`),
  INDEX `idproveidors_idx` (`proveidor` ASC) VISIBLE,
  UNIQUE INDEX `idulleres_UNIQUE` (`idulleres` ASC) VISIBLE,
  CONSTRAINT `idproveidors`
    FOREIGN KEY (`proveidor`)
    REFERENCES `ampolla`.`proveidors` (`idproveidors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`empleats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`empleats` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`empleats` (
  `idempleats` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idempleats`),
  UNIQUE INDEX `idempleats_UNIQUE` (`idempleats` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`recomanacio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`recomanacio` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`recomanacio` (
  `id_recomanacio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `recomanador_idclient` INT UNSIGNED NOT NULL,
  `recomanat_idclient1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_recomanacio`),
  INDEX `fk_clients_has_clients_clients2_idx` (`recomanat_idclient1` ASC) VISIBLE,
  INDEX `fk_clients_has_clients_clients1_idx` (`recomanador_idclient` ASC) VISIBLE,
  UNIQUE INDEX `id_recomanacio_UNIQUE` (`id_recomanacio` ASC) VISIBLE,
  CONSTRAINT `fk_clients_has_clients_clients1`
    FOREIGN KEY (`recomanador_idclient`)
    REFERENCES `ampolla`.`clients` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_has_clients_clients2`
    FOREIGN KEY (`recomanat_idclient1`)
    REFERENCES `ampolla`.`clients` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`clients` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`clients` (
  `idclient` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `mobil` VARCHAR(15) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(15) NOT NULL,
  `registre` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `adreca` INT UNSIGNED NOT NULL,
  `recomanacio` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `nif_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `idclient_UNIQUE` (`idclient` ASC) VISIBLE,
  INDEX `fk_clients_adreca1_idx` (`adreca` ASC) VISIBLE,
  UNIQUE INDEX `recomanacio_UNIQUE` (`recomanacio` ASC) VISIBLE,
  CONSTRAINT `fk_clients_adreca1`
    FOREIGN KEY (`adreca`)
    REFERENCES `ampolla`.`adreca` (`id_adreca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_recomanacio1`
    FOREIGN KEY (`recomanacio`)
    REFERENCES `ampolla`.`recomanacio` (`id_recomanacio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`factures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`factures` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`factures` (
  `idfactures` INT UNSIGNED NOT NULL,
  `idempleat` INT UNSIGNED NOT NULL,
  `total_itens` INT UNSIGNED NOT NULL,
  `valor_total` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idfactures`),
  INDEX `idempleats_idx` (`idempleat` ASC) VISIBLE,
  CONSTRAINT `idempleats`
    FOREIGN KEY (`idempleat`)
    REFERENCES `ampolla`.`empleats` (`idempleats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`carrito` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`carrito` (
  `clients_idclient` INT UNSIGNED NOT NULL,
  `factures_idfactures` INT NOT NULL,
  `ulleres_idulleres` INT UNSIGNED NOT NULL,
  `quantitat` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`clients_idclient`, `factures_idfactures`),
  INDEX `fk_clients_has_factures_factures1_idx` (`factures_idfactures` ASC) VISIBLE,
  INDEX `fk_clients_has_factures_clients1_idx` (`clients_idclient` ASC) VISIBLE,
  INDEX `fk_clients_has_factures_ulleres1_idx` (`ulleres_idulleres` ASC) VISIBLE,
  UNIQUE INDEX `ulleres_idulleres_UNIQUE` (`ulleres_idulleres` ASC) VISIBLE,
  CONSTRAINT `fk_clients_has_factures_clients1`
    FOREIGN KEY (`clients_idclient`)
    REFERENCES `ampolla`.`clients` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_has_factures_factures1`
    FOREIGN KEY (`factures_idfactures`)
    REFERENCES `ampolla`.`factures` (`idfactures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_has_factures_ulleres1`
    FOREIGN KEY (`ulleres_idulleres`)
    REFERENCES `ampolla`.`ulleres` (`idulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
