-- MySQL Script generated by MySQL Workbench
-- Mon May  4 22:25:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ampolla
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ampolla` ;

-- -----------------------------------------------------
-- Schema ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ampolla` DEFAULT CHARACTER SET utf8 ;
USE `ampolla` ;

-- -----------------------------------------------------
-- Table `ampolla`.`proveidors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`proveidors` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`proveidors` (
  `idproveidors` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` TINYINT(5) NOT NULL,
  `pis` TINYINT(3) NULL,
  `porta` TINYINT(2) NULL,
  `ciutat` VARCHAR(20) NOT NULL,
  `codi_postal` TINYINT(6) NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NULL,
  `nif` TINYINT(12) NOT NULL,
  PRIMARY KEY (`idproveidors`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`ulleres` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`ulleres` (
  `idulleres` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio` VARCHAR(45) NOT NULL,
  `muntura` ENUM('pasta', 'flotant', 'metal') NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidre` VARCHAR(45) NOT NULL,
  `preu` DECIMAL(6,2) NOT NULL,
  `proveidor` INT NULL,
  PRIMARY KEY (`idulleres`),
  INDEX `idproveidors_idx` (`proveidor` ASC) VISIBLE,
  CONSTRAINT `idproveidors`
    FOREIGN KEY (`proveidor`)
    REFERENCES `ampolla`.`proveidors` (`idproveidors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`empleats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`empleats` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`empleats` (
  `idempleats` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idempleats`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`clients` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`clients` (
  `idclient` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` TINYINT(5) NOT NULL,
  `pis` TINYINT(3) NULL,
  `porta` TINYINT(2) NULL,
  `ciutat` VARCHAR(20) NOT NULL,
  `codi_postal` TINYINT(6) NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `email` VARCHAR(25) NULL,
  `dni` TINYINT(12) NOT NULL,
  `registre` DATETIME NOT NULL,
  `recomanat` INT NULL,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `nif_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `idclient_idx` (`recomanat` ASC) VISIBLE,
  CONSTRAINT `idclient`
    FOREIGN KEY (`recomanat`)
    REFERENCES `ampolla`.`clients` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ampolla`.`factures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ampolla`.`factures` ;

CREATE TABLE IF NOT EXISTS `ampolla`.`factures` (
  `idfactures` INT NOT NULL,
  `idulleres` INT NOT NULL,
  `idclient` INT NOT NULL,
  `idempleat` INT NOT NULL,
  PRIMARY KEY (`idfactures`),
  INDEX `idulleres_idx` (`idulleres` ASC) VISIBLE,
  INDEX `idclient_idx` (`idclient` ASC) VISIBLE,
  INDEX `idempleats_idx` (`idempleat` ASC) VISIBLE,
  CONSTRAINT `idulleres`
    FOREIGN KEY (`idulleres`)
    REFERENCES `ampolla`.`ulleres` (`idulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idclient`
    FOREIGN KEY (`idclient`)
    REFERENCES `ampolla`.`clients` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idempleats`
    FOREIGN KEY (`idempleat`)
    REFERENCES `ampolla`.`empleats` (`idempleats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
