-- MySQL Script generated by MySQL Workbench
-- Mon May  4 20:07:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quadres
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quadres` ;

-- -----------------------------------------------------
-- Schema quadres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quadres` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema stube
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema amazon
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema xarxa
-- -----------------------------------------------------
USE `quadres` ;

-- -----------------------------------------------------
-- Table `quadres`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quadres`.`clients` ;

CREATE TABLE IF NOT EXISTS `quadres`.`clients` (
  `DNI` VARCHAR(9) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cognom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quadres`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quadres`.`stock` ;

CREATE TABLE IF NOT EXISTS `quadres`.`stock` (
  `idquadre` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `preu` DECIMAL(11,2) NOT NULL,
  `autor` VARCHAR(45) NULL DEFAULT 'anònim',
  `DNI_comprador` VARCHAR(9) NULL,
  PRIMARY KEY (`idquadre`),
  INDEX `DNI_idx` (`DNI_comprador` ASC) VISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI_comprador`)
    REFERENCES `quadres`.`clients` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
